### PR TITLE
Linux: rebuild BioSignalML libraries for GCC 5.4 (#1391)

### PR DESCRIPTION
**Pull request by dbrnz**

### CODE REVIEW

**Comment by dbrnz** [comment]
Not quite there yet @agarny. I've discovered that the uploaded `libbiosignalml.so` references the system's SSL libraries which apparently have symbols that aren't in OpenCOR's SSL libraries...

**Comment by agarny** [comment]
A couple of things:
 - I guess you meant to say GCC 5.4? As far as I am aware, GCC 5.5 doesn't exist (see [here](https://gcc.gnu.org/releases.html))?
 - When do you think your new binaries will be ready? It's just that I would like to get a new snapshot before I go on holiday (on 12 August) since it fixes a somewhat important problem (see issue #1385) and improves things for some modellers (see issue #1389). So, if for some reason or another, your new binaries were not to be ready, I would disable our BioSignalML-related plugins for the new snapshot.

**Comment by dbrnz** [comment]
Yes, I meant 5.4...

I'm testing things at the moment -- you'll have new binaries later on today.

**Comment by agarny** [comment]
Excellent, thanks a lot!

**Comment by dbrnz** [comment]
All good to go @agarny.

**Comment by agarny** [comment]
Great! :)

**Pull request merged**
